### ISSUE TITLE
Automatic Installation/Updating of Mods

### ISSUE THREAD

**Issue by mirddes** [ta-forever/downlords-taf-client#3]
**Is your feature request related to a problem? Please describe.**
I would like Mayhem, Escalation, Twilight, Zero and ProTA to automatically download and install when first joining/hosting a custom lobby.

**Describe the solution you'd like**
when first joining/hosting a custom lobby, or when a new version of an installed mod is released, TAF would download and apply the relevant files to duplicates of a source TA directory.

**Describe alternatives you've considered**
manually doing everything has been fine for the past 20 years, it's relatively straight forward if you're familiar with modding games but not idea for the games as a service generation.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/TAForever/downlords-taf-client)

**Comment by smross** [comment]
I've been testing this feature, and I'm wondering if adding content to this issue @Axle1975 is the best course of action (since it's only available on pre-release) or would you prefer a separate issue for what I'm finding?

As an example, I took the following approaches on a Dell laptop with a fresh Windows 10 install. Here's what the hardware looks like:

- Dell laptop
- Intel Core i7 CPU (2.6GHz)
- 16GB RAM
- Intel HD Graphics 530 + NVIDIA GeForce GTX 960M
- NVMe SSD
- Windows 10 Pro version 21H2, aka build `19044.1806`
- TAF version `1.4.3-taf-0.15.0` (first I installed the release client, then set TAF to check for pre-release, then updated automatically)

### ProTA 4.4 Manual Install

1. Update computer to current drivers, windows version, etc.
2. Install Total Annihilation via GOG installer ('offline downloader')
3. Move TA directory from GOG default to `C:\TAStuffz\Total Annihilation` (not modifying any files)
4. Copy the TA directory from `C:\TAStuffz\Total Annihilation` to `C:\TAStuffz\ProTA`
5. Create a game
6. Launch ProTA, configure resolution (1920x1080), start game, it works

### ProTA 4.4 TAF Install

1. Update computer to current drivers, windows version, etc.
2. Install Total Annihilation via GOG installer ('offline downloader')
3. Move TA directory from GOG default to `C:\TAStuffz\Total Annihilation` (not modifying any files)
4. Download TAF Client and install
5. Configure TAF Client to point to the TA install at `C:\TAStuffz\Total Annihilation` for it's _Core Contingency_ setting
8. Configure TAF to use a pre-release version, install, and restart TAF Client
9. Create a game in TAF Client and select 'ProTA' as the mod
10. Follow the option/wizard to install ProTA and let TAF do it's thing, installing ProTA to `C:\TAStuffz\ProTA`
11. Close TAF Client
12. Navigate to ProTA directory (from auto install) and delete pdraw.dll (this is the only way ProTA would launch for me)
13. Launch ProTA (outside of TAF Client) from the auto-installed directory; for me this is `C:\TAStuffz\ProTA\Totala.exe`
14. Configure resolution, start game
15. TA works, but has the following issues:
    * Resolution is not 1920x1080 (at least it's not scaled/sized the same as manually installed ProTA)
    * Hotkeys/keyboard shortcuts do not work

### File comparison/differential
I also ran a folder and file comparison to see how things are different. It's attached (below)
[Folder Compare-ProTA Manual vs ProTA TAF.pdf](https://github.com/ta-forever/downlords-taf-client/files/9007410/Folder.Compare-ProTA.Manual.vs.ProTA.TAF.pdf)

**Comment by Axle1975** [comment]
thanks @smross that's great information.  I'll look into why the resolution isn't being set properly.  And I haven't actually tested the hotkeys/keboard shortcuts, I'll defo have to fix that

**Comment by smross** [comment]
NP @Axle1975 ... I guess I'm wondering why the file structure is so different between manual ProTA and TAF ProTA. I'm not familiar w/ TA's file structure and code, or how TAF is taking a 'Core Contingency' TA install and duplicating it in the ProTA directory plus adding the ProTA files.

Here are the files that stand out to me (why don't they exist in TAF ProTA)...
* AFark.ufo
* AFlea.ufo
* AScarab.ufo
* ccmiss.ccx
* Cormabm.ufo
* CorNecro.ufo
* corplas.ufo
* Evadrivd.ufo
* floggen.ufo
* mptaext.dll
* pdraw.dll (obviously this is because I removed it manually...)
* rev31.gp3
* tactics1.hpi
* tactics2.hpi
* tactics3.hpi
* tactics4.hpi
* tactics5.hpi
* tactics6.hpi
* tactics7.hpi
* tactics8.hpi
* tadwnqox.dll
* tae.exe
* tae.hlp
* taheatx.dll
* tamplayx.dll
* tatenx.dll
* tawirepx.dll
* win32.dll
* worlds.hpi

Some of the files are maps, and I've tried to exclude those from the above list. The file `tademo.ufo` is another interesting case as it is included with TAF ProTA but _does not_ exist in my manually installed ProTA. Also, the folders `.git` and `log` exist in TAF ProTA (but not manual). I'm sure they don't hurt anything, but wanted to be thorough.

I have multiple systems available, so if you need help testing or comparing processes, let me know.

**Comment by Axle1975** [comment]
I created a new issue to capture the hotkey and screen resolution issue #55
